[package]
name = "counter"
version = "0.1.0"
authors = ["kenjinp <github@kenny.wtf>"]
edition = "2018"

[dependencies]
stdweb = "0.4.2"
rand = { version = "0.5.5",  features = ["stdweb"] }
yew = { git = "https://github.com/DenisKolodin/yew", features = ["toml"] }